---
# tasks file for idm

- name: Generate Installer command - First Pass
  set_fact:
    idm_deployment_installer_args: "{{ idm_deployment_installer_args }}
      --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ idm_deployment_answers }}"

- name: Generate Installer command - Second Pass
  set_fact:
    idm_deployment_installer_args: "{{ idm_deployment_installer_args }}
      --{{ item.key }}"
  with_dict: "{{ idm_deployment_answers_bools }}"
  when: item.value

- name: Run Identity Management setup
  command: "ipa-server-install {{ idm_deployment_installer_args }}"
  register: command_result
  failed_when: "'already configured' not in command_result.stderr"
  tags:
    - idm
    - install

